# pytorch 学习第一节

In [1]:
import torch

创建随机矩阵

In [2]:
torch.empty(5,3)

tensor([[-2.2205e-10,  7.8333e-43, -2.2205e-10],
        [ 7.8333e-43, -2.2205e-10,  7.8333e-43],
        [-2.2205e-10,  7.8333e-43, -2.2205e-10],
        [ 7.8333e-43, -2.2205e-10,  7.8333e-43],
        [-2.2205e-10,  7.8333e-43, -2.2205e-10]])

In [3]:
torch.rand(5,3)

tensor([[0.0795, 0.7541, 0.3451],
        [0.7705, 0.8598, 0.7178],
        [0.9065, 0.0876, 0.8736],
        [0.9985, 0.7994, 0.3776],
        [0.5021, 0.6566, 0.8445]])

生成全0矩阵,和numberpy一样的操作，可以设置数据类型，查询shape等

In [4]:
x=torch.zeros(5,3,dtype=torch.long)
x=torch.zeros(5,3).long()
x.dtype

torch.int64

直接从数据中构建tensor

In [5]:
x=torch.tensor([5.3,3])
x

tensor([5.3000, 3.0000])

从已有的tensor中构建出新的tensor，会复用原有tensor的数据类型等信息。也可以明确指定tensor的数据类型

In [6]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

生成和已有的tensor一样的shape的随机数矩阵，可以指定类型

In [7]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[ 0.1239, -2.0162, -0.4906],
        [-0.9685, -0.6562, -0.1740],
        [ 1.0220, -1.3986,  1.7798],
        [-1.2376, -0.2197, -1.8547],
        [ 0.4820, -0.3438,  1.1398]])

In [8]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

生成和已有的tensor一样的shape的随机数矩阵，可以指定类型

In [9]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[-2.1046,  0.6274,  1.8916],
        [ 0.1583, -0.3258, -0.9288],
        [-0.7057, -0.1669,  0.4433],
        [ 0.4244,  0.6196,  0.3268],
        [-0.2700,  0.5701, -1.2374]])

获取tensor的尺寸

In [10]:
x.shape

torch.Size([5, 3])

torch的操作符运算

In [11]:
y=torch.rand(5,3)
y

tensor([[0.8864, 0.0444, 0.8591],
        [0.0799, 0.8801, 0.2116],
        [0.2084, 0.4143, 0.2776],
        [0.8094, 0.7290, 0.9938],
        [0.6685, 0.3323, 0.4692]])

In [12]:
x+y

tensor([[-1.2183,  0.6718,  2.7506],
        [ 0.2382,  0.5544, -0.7172],
        [-0.4973,  0.2474,  0.7210],
        [ 1.2338,  1.3486,  1.3206],
        [ 0.3985,  0.9024, -0.7682]])

In [13]:
torch.add(x,y)

tensor([[-1.2183,  0.6718,  2.7506],
        [ 0.2382,  0.5544, -0.7172],
        [-0.4973,  0.2474,  0.7210],
        [ 1.2338,  1.3486,  1.3206],
        [ 0.3985,  0.9024, -0.7682]])

使用out会减少一次内存分配

In [14]:
result=torch.empty(5,3)
# torch.add(x,y,out=result)
# result=torch.add(x,y)
print(result)
result=x+y
result

tensor([[9.0918e-39, 9.1837e-39, 8.4490e-39],
        [9.6428e-39, 1.1112e-38, 9.5511e-39],
        [1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38]])


tensor([[-1.2183,  0.6718,  2.7506],
        [ 0.2382,  0.5544, -0.7172],
        [-0.4973,  0.2474,  0.7210],
        [ 1.2338,  1.3486,  1.3206],
        [ 0.3985,  0.9024, -0.7682]])

In [15]:
y
y.add_(x)
y

tensor([[-1.2183,  0.6718,  2.7506],
        [ 0.2382,  0.5544, -0.7172],
        [-0.4973,  0.2474,  0.7210],
        [ 1.2338,  1.3486,  1.3206],
        [ 0.3985,  0.9024, -0.7682]])

In [16]:
x=torch.randn(4,4)
x

tensor([[ 0.0260, -2.6393,  0.0557, -0.3855],
        [ 0.7576,  1.5856,  0.7353,  0.8154],
        [ 1.0978,  0.2432,  1.7738, -0.0914],
        [ 1.2339,  1.0665, -1.2281, -1.2069]])

In [17]:
y=x.view(16)
z=x.view(8,-1)
y
z

tensor([[ 0.0260, -2.6393],
        [ 0.0557, -0.3855],
        [ 0.7576,  1.5856],
        [ 0.7353,  0.8154],
        [ 1.0978,  0.2432],
        [ 1.7738, -0.0914],
        [ 1.2339,  1.0665],
        [-1.2281, -1.2069]])

如果tensor只有一个元素  可以用item直接获取值

In [18]:
x=torch.tensor([1])
x.item()

1

In [19]:
y

tensor([ 0.0260, -2.6393,  0.0557, -0.3855,  0.7576,  1.5856,  0.7353,  0.8154,
         1.0978,  0.2432,  1.7738, -0.0914,  1.2339,  1.0665, -1.2281, -1.2069])

In [20]:
y.transpose(-1,0)

tensor([ 0.0260, -2.6393,  0.0557, -0.3855,  0.7576,  1.5856,  0.7353,  0.8154,
         1.0978,  0.2432,  1.7738, -0.0914,  1.2339,  1.0665, -1.2281, -1.2069])

tensor 转 numpy 共享一段内存，一个改另一个也改

In [21]:
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [22]:
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [23]:
a[2]=2
b

array([1., 1., 2., 1., 1.], dtype=float32)

In [24]:
c=torch.from_numpy(b)
c
c[3]=5
a

tensor([1., 1., 2., 5., 1.])

## torch 在gpu上运行

In [25]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

转numpy

In [26]:
z.cpu().data.numpy()
z.to("cpu").data.numpy()

array([[ 0.02599315, -2.6393068 ],
       [ 0.05569734, -0.385459  ],
       [ 0.7576474 ,  1.5856093 ],
       [ 0.73526704,  0.8154471 ],
       [ 1.0977694 ,  0.24323305],
       [ 1.7737609 , -0.09136716],
       [ 1.2339412 ,  1.066541  ],
       [-1.2281259 , -1.2069428 ]], dtype=float32)

## numpy实现两层神经网络


一个全连接的ReLu神经网络，一个隐藏层 没有bias 用x预测y 使用L2 loss

- $ h=W_1x+b $
- $ a=max(0,h) $
- $ y_{hat}=W_2a+b_2 $

计算前向神经网络 loss  和反向传播

- forward pass
- loss 
- backward pass

## torch 在gpu上运行

In [27]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

转numpy

In [28]:
z.cpu().data.numpy()
z.to("cpu").data.numpy()

array([[ 0.02599315, -2.6393068 ],
       [ 0.05569734, -0.385459  ],
       [ 0.7576474 ,  1.5856093 ],
       [ 0.73526704,  0.8154471 ],
       [ 1.0977694 ,  0.24323305],
       [ 1.7737609 , -0.09136716],
       [ 1.2339412 ,  1.066541  ],
       [-1.2281259 , -1.2069428 ]], dtype=float32)

## numpy实现两层神经网络


一个全连接的ReLu神经网络，一个隐藏层 没有bias 用x预测y 使用L2 loss

- $ h=W_1x+b $
- $ a=max(0,h) $
- $ y_{hat}=W_2a+b_2 $

计算前向神经网络 loss  和反向传播

- forward pass
- loss 
- backward pass

In [29]:
import numpy as np
N,D_in,H,D_out=64,1000,100,10
#随机创建一些训练数据
x=np.random.randn(N,D_in)
y=np.random.randn(N,D_out)
w1=np.random.randn(D_in,H)
w2=np.random.randn(H,D_out)
learning_rate=1e-6
for i in range(500):
    # Forward pass
    h=x.dot(w1) # N*H
    h_relu=np.maximum(h,0) # N*H
    y_pred=h_relu.dot(w2)# N*D_out
    # compute loss
    loss =np.square(y_pred-y).sum()
    print(i,loss)
    # Backward pass
    # compute the gradient
    grad_y_pred=2.0*(y_pred-y)
    grad_w2=h_relu.T.dot(grad_y_pred)
    grad_h_relu=grad_y_pred.dot(w2.T)
    grad_h=grad_h_relu.copy()
    grad_h[h<0]=0
    grad_w1=x.T.dot(grad_h)
    # update weights of w1 and w2
    w1-=learning_rate*grad_w1
    w2-=learning_rate*grad_w2
    

0 34490797.553979196
1 32361940.502169706
2 33121650.876532573
3 31152796.309701607
4 24736130.28871373
5 16048516.160462392
6 9007168.199758252
7 4776361.243118847
8 2657610.5761881517
9 1639346.5969158055
10 1132526.4464088557
11 853878.401362584
12 681821.1690041369
13 563350.4466768256
14 475071.47068733536
15 405717.1728862182
16 349576.16407728195
17 303126.2281572481
18 264181.43037175236
19 231232.52638584503
20 203178.51346235807
21 179170.61978949676
22 158524.77523093973
23 140695.1347227424
24 125228.90258237743
25 111754.55289724786
26 99985.5884478899
27 89676.786680729
28 80619.51556366432
29 72632.58849595941
30 65574.39038690901
31 59322.74586978
32 53763.695057873585
33 48812.75014964894
34 44392.57013687742
35 40436.60019695779
36 36890.56454967636
37 33704.19340354587
38 30837.051328678783
39 28252.873408108382
40 25919.344178303127
41 23809.585449586808
42 21898.365445998705
43 20164.35082605271
44 18589.989848388774
45 17157.169789991247
46 15852.239340923903
47 1

373 0.005674609012340855
374 0.005450220840365942
375 0.00523475299921218
376 0.005027803661457634
377 0.00482905688935296
378 0.004638290393976587
379 0.004454909853348728
380 0.0042788305083867545
381 0.004109721423731347
382 0.003947288193509311
383 0.0037913947671674303
384 0.0036415767381539317
385 0.0034976841060127073
386 0.0033595048772653647
387 0.0032267681490231086
388 0.003099260069761112
389 0.0029767838347176216
390 0.0028591591713516933
391 0.0027462134388850836
392 0.0026377107384361054
393 0.0025335617529740665
394 0.0024334841446366808
395 0.002337355799813435
396 0.002245040203351822
397 0.0021563638629350022
398 0.0020711953852909273
399 0.0019893721113699693
400 0.001910807616849915
401 0.0018353697647882838
402 0.0017628747021181802
403 0.0016932645950409604
404 0.001626401829941585
405 0.0015621689240411982
406 0.001500466108135278
407 0.00144121192846829
408 0.0013843226615322252
409 0.0013296744926116614
410 0.0012771760409181297
411 0.0012267459047251832
412 0

In [30]:
x

array([[-0.91204805,  1.1130183 ,  0.36121444, ...,  0.44128317,
         0.24519763, -0.51518435],
       [-0.23086129, -1.01643722, -0.64565103, ...,  0.02686055,
        -0.21493675, -0.42472752],
       [-1.41958549,  0.45823412,  0.15634979, ...,  0.60146188,
         0.30766432, -1.0712045 ],
       ...,
       [-1.11564303,  0.98021827,  0.04945   , ..., -0.27056274,
        -1.02223624,  0.42496605],
       [-0.81136346, -1.36353538,  0.59276533, ...,  0.93695776,
        -0.06116057, -1.28309753],
       [ 0.15656473, -0.91187907,  0.43266799, ...,  0.10974753,
        -1.6918163 ,  0.73620744]])

In [31]:
y

array([[-4.58772374e-01, -1.98787907e+00,  1.32152011e+00,
         7.29545962e-01,  1.23896584e+00, -1.81859648e+00,
         2.59785380e-01,  4.41076961e-01,  6.47272792e-01,
        -7.62720742e-01],
       [-1.11748991e+00,  1.18937092e+00, -2.13151621e-01,
        -2.73841780e-01, -1.07038248e+00, -1.27714470e+00,
        -1.48423202e+00,  2.28733084e+00,  7.30249624e-01,
        -1.35232550e-01],
       [-2.86731024e-01, -3.15089059e-01,  1.08084368e+00,
        -6.60245210e-01, -4.25503662e-01, -3.61635074e-01,
        -1.00800133e+00, -1.56037920e+00,  1.36659568e+00,
        -1.64596400e+00],
       [-1.50462184e+00, -1.55916712e+00, -9.05690412e-01,
         7.52060747e-01,  2.68754817e-01, -1.10785809e+00,
         2.34654345e-01,  2.20828028e-01, -4.91546784e-01,
         4.27950022e-01],
       [ 7.97148344e-02,  6.96330251e-01,  1.07376478e+00,
        -1.07227388e+00, -1.02114216e-01, -3.39014645e-01,
        -9.67929452e-01, -8.99977168e-01,  3.24578797e-01,
         1.

In [32]:
h=x.dot(w1)
h_relu=np.maximum(h,0)
y_pred=h_relu.dot(w2)
y_pred-y

array([[-2.07345983e-04, -9.51837798e-05, -8.08406216e-05,
         3.76330270e-05, -1.68157918e-04, -3.64940865e-04,
         3.43795976e-04,  2.25648873e-04, -3.94086516e-04,
        -3.25574006e-04],
       [-8.53600741e-05, -1.81197898e-04, -1.07307241e-04,
         1.38430463e-04,  1.12990964e-04, -1.82445348e-04,
         1.83943618e-04,  1.30294433e-04, -1.91960461e-04,
        -1.04188292e-04],
       [-1.83335116e-04, -2.70625913e-04, -8.68615139e-05,
         1.17290997e-04,  8.57678863e-05, -2.82791113e-04,
         3.75309567e-04,  2.07008929e-04, -4.81073046e-04,
        -2.33213062e-04],
       [ 7.47014004e-05,  1.91348112e-04,  9.40608343e-05,
         2.52589165e-06, -1.89786435e-05,  2.77250878e-04,
        -2.43827444e-04, -1.39151013e-04,  2.75458833e-04,
         2.25004816e-04],
       [ 5.66565863e-05,  6.29617023e-05,  5.66861661e-05,
        -5.16478055e-05, -4.45272677e-06,  8.69097231e-05,
        -1.14400912e-04, -6.31769889e-05,  1.47772862e-04,
         9.

numpy 转 pytorch

In [33]:
N,D_in,H,D_out=64,1000,100,10
#随机创建一些训练数据
x=torch.randn(N,D_in)
y=torch.randn(N,D_out)
w1=torch.randn(D_in,H)
w2=torch.randn(H,D_out)
learning_rate=1e-6
for i in range(500):
    # Forward pass
    h=x.mm(w1) # N*H
    h_relu=h.clamp(min=0) # N*H
    y_pred=h_relu.mm(w2)# N*D_out
    # compute loss
    loss =(y_pred-y).pow(2).sum().item()
    print(i,loss)
    # Backward pass
    # compute the gradient
    grad_y_pred=2.0*(y_pred-y)
    grad_w2=h_relu.t().mm(grad_y_pred)
    grad_h_relu=grad_y_pred.mm(w2.T)
    grad_h=grad_h_relu.clone()
    grad_h[h<0]=0
    grad_w1=x.t().mm(grad_h)
    # update weights of w1 and w2
    w1-=learning_rate*grad_w1
    w2-=learning_rate*grad_w2
    

0 40106192.0
1 42895136.0
2 52805380.0
3 55425232.0
4 40671256.0
5 18916608.0
6 6748678.0
7 2783808.5
8 1654328.625
9 1231208.25
10 995407.125
11 828233.375
12 698353.9375
13 593826.6875
14 508475.90625
15 438132.5
16 379960.78125
17 331118.8125
18 289894.3125
19 254945.5
20 225028.65625
21 199283.765625
22 177048.46875
23 157772.3125
24 140959.125
25 126248.96875
26 113333.4921875
27 101952.265625
28 91893.0078125
29 82990.2265625
30 75080.0
31 68035.921875
32 61750.1484375
33 56126.9140625
34 51087.15234375
35 46557.87890625
36 42481.796875
37 38807.8984375
38 35490.37890625
39 32490.234375
40 29772.9609375
41 27307.6875
42 25069.400390625
43 23033.5390625
44 21180.572265625
45 19491.896484375
46 17951.58984375
47 16544.65625
48 15257.912109375
49 14080.3876953125
50 13001.5244140625
51 12013.763671875
52 11107.6611328125
53 10275.8623046875
54 9512.8515625
55 8811.7294921875
56 8166.728515625
57 7572.94775390625
58 7025.58154296875
59 6520.66259765625
60 6055.02099609375
61 5624.978

387 0.0004168945306446403
388 0.0004047381808049977
389 0.0003940688620787114
390 0.0003831361827906221
391 0.00037267443258315325
392 0.0003614975430537015
393 0.00035169909824617207
394 0.0003419664571993053
395 0.0003328080056235194
396 0.0003246970009058714
397 0.00031528910039924085
398 0.00030625227373093367
399 0.0002982045407406986
400 0.000290979485725984
401 0.00028349066269584
402 0.0002769403508864343
403 0.0002697679155971855
404 0.0002628465590532869
405 0.0002560430730227381
406 0.00024918405688367784
407 0.00024299816868733615
408 0.0002366329135838896
409 0.00023134058574214578
410 0.00022581734810955822
411 0.00021983467740938067
412 0.00021482675219886005
413 0.00020980056433472782
414 0.00020475561905186623
415 0.0002001859829761088
416 0.00019560207147151232
417 0.00019078291370533407
418 0.0001868562976596877
419 0.0001823516795411706
420 0.00017787523393053561
421 0.0001735529804136604
422 0.0001700394495856017
423 0.0001660400303080678
424 0.00016249442705884576

In [34]:
x=torch.tensor(1.,requires_grad=True)
w=torch.tensor(2.,requires_grad=True)
b=torch.tensor(1.,requires_grad=True)
y=w*x+b
y.backward()
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [35]:
x=torch.tensor(1.,requires_grad=True)
w=torch.tensor(2.,requires_grad=True)
b=torch.tensor(1.,requires_grad=True)
y=w*x+b
y.backward()
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


## numpy 转 pytorch 简化

In [36]:
N,D_in,H,D_out=64,1000,100,10
#随机创建一些训练数据
x=torch.randn(N,D_in)
y=torch.randn(N,D_out)
w1=torch.randn(D_in,H,requires_grad=True)
w2=torch.randn(H,D_out,requires_grad=True)
learning_rate=1e-6
for i in range(500):
    # forward pass
    y_pred=x.mm(w1).clamp(min=0).mm(w2)
    #loss function
    loss=(y_pred-y).pow(2).sum()
    print(i,loss.item())
    # backward pass
    loss.backward()
    w1-=learning_rate*w1.grad
    w2-=learning_rate*w2.grad
    

0 31631740.0


RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [45]:
N,D_in,H,D_out=64,1000,100,10
#随机创建一些训练数据
x=torch.randn(N,D_in)
y=torch.randn(N,D_out)
w1=torch.randn(D_in,H,requires_grad = True)
w2=torch.randn(H,D_out,requires_grad = True)
learning_rate=1e-6
for i in range(500):
    # forward pass
    y_pred=x.mm(w1).clamp(min=0).mm(w2)
    #loss function
    loss=(y_pred-y).pow(2).sum()
    print(i,loss.item())
    w1.retain_grad() 
    w2.retain_grad() 
    # backward pass
    loss.backward()
    w1= w1 - learning_rate*w1.grad
    w2= w2 - learning_rate*w2.grad
    

0 41139600.0
1 38769744.0
2 36280412.0
3 28726158.0
4 18198322.0
5 9779514.0
6 5112737.0
7 2967530.5
8 1990228.0
9 1493336.625
10 1196301.75
11 992345.0625
12 838932.125
13 717369.625
14 618440.375
15 536581.125
16 468028.125
17 410165.78125
18 361015.125
19 319011.40625
20 282885.25
21 251755.84375
22 224842.578125
23 201378.59375
24 180849.8125
25 162804.25
26 146891.390625
27 132813.390625
28 120328.8125
29 109229.078125
30 99349.7109375
31 90529.203125
32 82629.890625
33 75546.6484375
34 69171.75
35 63420.0390625
36 58231.796875
37 53541.69921875
38 49287.265625
39 45421.72265625
40 41904.71484375
41 38699.91796875
42 35777.5078125
43 33107.47265625
44 30664.458984375
45 28426.927734375
46 26374.583984375
47 24490.771484375
48 22759.8203125
49 21166.9921875
50 19700.013671875
51 18347.77734375
52 17100.59375
53 15948.7197265625
54 14884.1240234375
55 13899.16796875
56 12987.3251953125
57 12142.4296875
58 11359.3740234375
59 10632.8046875
60 9958.1201171875
61 9331.4462890625
62 874

387 0.01090901531279087
388 0.010525858961045742
389 0.010160686448216438
390 0.009808720089495182
391 0.00946478545665741
392 0.009133200161159039
393 0.008814705535769463
394 0.008508242666721344
395 0.008213816210627556
396 0.007923834957182407
397 0.007652118802070618
398 0.007393130101263523
399 0.007138698361814022
400 0.006893823854625225
401 0.006656639277935028
402 0.006429467815905809
403 0.006206906400620937
404 0.005995496641844511
405 0.005795040633529425
406 0.005597109906375408
407 0.00540904002264142
408 0.005227982997894287
409 0.005053089465945959
410 0.004882503766566515
411 0.004719313234090805
412 0.004559744615107775
413 0.004409365821629763
414 0.004262571223080158
415 0.004123585764318705
416 0.0039856769144535065
417 0.003856687108054757
418 0.0037332570645958185
419 0.0036107671912759542
420 0.0034887914080172777
421 0.0033817486837506294
422 0.0032695115078240633
423 0.003167426446452737
424 0.003061822149902582
425 0.0029670840594917536
426 0.002872282871976

## PYTORCH NN

In [47]:
N,D_in,H,D_out=64,1000,100,10
import torch.nn as nn
x=torch.randn(N,D_in)
y=torch.randn(N,D_out)
model=nn.Sequential(
    nn.Linear(D_in,H),# w1*x + b1
    nn.ReLU(),
    nn.Linear(H,D_out)
)
loss_func=nn.MSELoss(reduction="sum")
learning_rate=1e-6
for i in range(500):
    y_pre=model(x) #forward pass
    loss=loss_func(y_pre,y)
    print(loss.item())
    loss.backward()
    with torch.no_grad():
        for param in model.parameters():
            param-=learning_rate*param.grad

683.828125
683.2854614257812
682.2014770507812
680.5795288085938
678.4288330078125
675.7592163085938
672.5725708007812
668.8870239257812
664.74755859375
660.1400146484375
655.0768432617188
649.5670166015625
643.6328735351562
637.2977905273438
630.5707397460938
623.4752197265625
616.0504150390625
608.3064575195312
600.261962890625
591.9365234375
583.340576171875
574.4859619140625
565.4183349609375
556.1701049804688
546.7772216796875
537.2464599609375
527.6892700195312
518.0390625
508.2991943359375
498.4898681640625
488.65130615234375
478.78033447265625
468.9232177734375
459.1251525878906
449.3688659667969
439.6444091796875
429.9738464355469
420.33111572265625
410.7840881347656
401.3326416015625
391.9610290527344
382.6902160644531
373.55712890625
364.6012878417969
355.8320007324219
347.20465087890625
338.7430114746094
330.4302978515625
322.26763916015625
314.26495361328125
306.4344787597656
298.7890625
291.33416748046875
284.07684326171875
277.026123046875
270.15594482421875
263.50848388

212.59829711914062
215.22450256347656
216.88255310058594
217.53179931640625
217.15374755859375
215.75848388671875
213.3843994140625
210.0921173095703
205.9656524658203
201.1143798828125
195.6720733642578
189.75758361816406
183.52255249023438
177.11843872070312
170.70298767089844
164.4381103515625
158.4776611328125
152.95941162109375
148.0126190185547
143.75852966308594
140.29180908203125
137.68896484375
136.00502014160156
135.26589965820312
135.478515625
136.63040161132812
138.6818389892578
141.5704803466797
145.21316528320312
149.51226806640625
154.3468780517578
159.58438110351562
165.09146118164062
170.71783447265625
176.3080291748047
181.71072387695312
186.80319213867188
