# pytorch 学习第一节

In [1]:
import torch

创建随机矩阵

In [2]:
torch.empty(5,3)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.4619e+15],
        [8.3517e-43, 0.0000e+00, 0.0000e+00],
        [4.4619e+15, 8.3517e-43, 4.4620e+15]])

In [3]:
torch.rand(5,3)

tensor([[0.0680, 0.1212, 0.2489],
        [0.7089, 0.1546, 0.7516],
        [0.9396, 0.9004, 0.8264],
        [0.9060, 0.7763, 0.7869],
        [0.7882, 0.7859, 0.7325]])

生成全0矩阵,和numberpy一样的操作，可以设置数据类型，查询shape等

In [4]:
x=torch.zeros(5,3,dtype=torch.long)
x=torch.zeros(5,3).long()
x.dtype

torch.int64

直接从数据中构建tensor

In [5]:
x=torch.tensor([5.3,3])
x

tensor([5.3000, 3.0000])

从已有的tensor中构建出新的tensor，会复用原有tensor的数据类型等信息。也可以明确指定tensor的数据类型

In [6]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

生成和已有的tensor一样的shape的随机数矩阵，可以指定类型

In [5]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[ 1.1457,  0.9487,  0.2178],
        [ 0.3746,  1.3100,  1.4054],
        [-1.1810,  0.6476,  1.0142],
        [-0.8678, -0.4694, -1.0189],
        [-0.5754,  0.6436, -0.9185]])

In [8]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

生成和已有的tensor一样的shape的随机数矩阵，可以指定类型

In [9]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[-2.0594,  0.1367,  0.4106],
        [ 1.1327, -0.2244,  0.9997],
        [ 0.8423,  1.3963,  0.1467],
        [-0.7257,  0.6424, -1.5615],
        [-1.2722, -0.6785, -0.7650]])

获取tensor的尺寸

In [12]:
x.shape

torch.Size([5, 3])

torch的操作符运算

In [52]:
y=torch.rand(5,3)
y

tensor([[0.0744, 0.1148, 0.6163],
        [0.5723, 0.8796, 0.7599],
        [0.3265, 0.3368, 0.2739],
        [0.0556, 0.9895, 0.1049],
        [0.3726, 0.4788, 0.7022]])

In [15]:
x+y

tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])

In [16]:
torch.add(x,y)

tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])

使用out会减少一次内存分配

In [18]:
result=torch.empty(5,3)
# torch.add(x,y,out=result)
# result=torch.add(x,y)
print(result)
result=x+y
result

tensor([[2.7049e-17, 4.5821e-41, 2.7049e-17],
        [4.5821e-41, 6.6815e+15, 3.0739e-41],
        [1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.5821e-41],
        [0.0000e+00, 0.0000e+00, 4.6243e-44]])
tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])
tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])


tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])

In [23]:
y
y.add_(x)
y

tensor([[-3.3399,  0.7633,  1.2560],
        [ 2.4035, -0.2059,  2.0677],
        [ 2.6750,  3.1670,  1.2032],
        [-0.8221,  1.4417, -2.9340],
        [-2.1699, -0.7118, -1.0487]])

In [47]:
x=torch.randn(4,4)
x

tensor([[ 0.4096,  1.1041, -0.5462,  0.1856],
        [-0.1747,  0.5966, -1.2375, -0.8923],
        [-1.5111,  0.1223, -0.4714,  0.0083],
        [-0.3921,  0.8738,  0.1272, -0.3974]])

In [36]:
y=x.view(16)
z=x.view(8,-1)
y
z

ValueError: only one element tensors can be converted to Python scalars

如果tensor只有一个元素  可以用item直接获取值

In [38]:
x=torch.tensor([1])
x.item()

1

In [59]:
y

tensor([[0.0744, 0.1148, 0.6163],
        [0.5723, 0.8796, 0.7599],
        [0.3265, 0.3368, 0.2739],
        [0.0556, 0.9895, 0.1049],
        [0.3726, 0.4788, 0.7022]])

In [58]:
y.transpose(-1,0)

tensor([[0.0744, 0.5723, 0.3265, 0.0556, 0.3726],
        [0.1148, 0.8796, 0.3368, 0.9895, 0.4788],
        [0.6163, 0.7599, 0.2739, 0.1049, 0.7022]])

tensor 转 numpy 共享一段内存，一个改另一个也改

In [61]:
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [71]:
b=a.numpy()
b

array([1., 2., 2., 1., 1.], dtype=float32)

In [72]:
a[2]=2
b

array([1., 2., 2., 1., 1.], dtype=float32)

In [ ]:
c=torch.from_numpy(b)
c
c[3]=5
a

## torch 在gpu上运行

In [ ]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

转numpy

In [ ]:
z.cpu().data.numpy()
z.to("cpu").data.numpy()

## numpy实现两层神经网络


一个全连接的ReLu神经网络，一个隐藏层 没有bias 用x预测y 使用L2 loss

- $ h=W_1x+b $
- $ a=max(0,h) $
- $ y_{hat}=W_2a+b_2 $

计算前向神经网络 loss  和反向传播

- forward pass
- loss 
- backward pass

tensor([1., 2., 2., 5., 1.])

## torch 在gpu上运行

In [77]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

False

转numpy

In [ ]:
z.cpu().data.numpy()
z.to("cpu").data.numpy()

## numpy实现两层神经网络


一个全连接的ReLu神经网络，一个隐藏层 没有bias 用x预测y 使用L2 loss

- $ h=W_1x+b $
- $ a=max(0,h) $
- $ y_{hat}=W_2a+b_2 $

计算前向神经网络 loss  和反向传播

- forward pass
- loss 
- backward pass

In [8]:
import numpy as np
N,D_in,H,D_out=64,1000,100,10
#随机创建一些训练数据
x=np.random.randn(N,D_in)
y=np.random.randn(N,D_out)
w1=np.random.randn(D_in,H)
w2=np.random.randn(H,D_out)
learning_rate=1e-6
for i in range(500):
    # Forward pass
    h=x.dot(w1) # N*H
    h_relu=np.maximum(h,0) # N*H
    y_pred=h_relu.dot(w2)# N*D_out
    # compute loss
    loss =np.square(y_pred-y).sum()
    print(i,loss)
    # Backward pass
    # compute the gradient
    grad_y_pred=2.0*(y_pred-y)
    grad_w2=h_relu.T.dot(grad_y_pred)
    grad_h_relu=grad_y_pred.dot(w2.T)
    grad_h=grad_h_relu.copy()
    grad_h[h<0]=0
    grad_w1=x.T.dot(grad_h)
    # update weights of w1 and w2
    w1-=learning_rate*grad_w1
    w2-=learning_rate*grad_w2
    

0 43033182.26828489
1 42894400.170374304
2 39713920.58362867
3 29142438.74748133
4 16637013.515335554
5 8115805.679354563
6 4088069.3973143967
7 2405466.3411081666
8 1661257.1924571823
9 1270179.3900668682
10 1023634.6511177887
11 847175.3466584745
12 711441.6125619072
13 603313.3421649972
14 515367.57234898617
15 442867.2242691413
16 382532.0991335006
17 331992.00286490587
18 289386.48924529174
19 253314.09032978656
20 222586.2967142596
21 196298.28212203912
22 173647.58912220376
23 154072.1468818813
24 137080.49959670007
25 122267.0407193893
26 109305.73712633154
27 97925.26985530682
28 87915.22556717006
29 79101.09577863404
30 71295.79470424939
31 64370.44015935834
32 58213.47966943028
33 52725.83172868812
34 47824.10062409006
35 43439.220839048874
36 39508.10060782162
37 35977.2466597203
38 32801.90413824083
39 29943.401043265858
40 27364.306386262222
41 25033.30068397477
42 22923.96756060458
43 21013.166626122005
44 19279.470831911924
45 17705.365929485153
46 16275.438935035467
47