# pytorch 学习第一节

In [1]:
import torch

创建随机矩阵

In [2]:
torch.empty(5,3)

tensor([[-6.3470e+29,  4.5820e-41, -6.3611e+29],
        [ 4.5820e-41, -6.3472e+29,  4.5820e-41],
        [ 6.7168e+15,  3.0739e-41, -6.5748e+29],
        [ 4.5820e-41,  6.7174e+15,  3.0739e-41],
        [ 6.7179e+15,  3.0739e-41,  5.5220e+15]])

In [3]:
torch.rand(5,3)

tensor([[0.2282, 0.8998, 0.0200],
        [0.4974, 0.1100, 0.0691],
        [0.7728, 0.8181, 0.4499],
        [0.4451, 0.2819, 0.9275],
        [0.6880, 0.5682, 0.4771]])

生成全0矩阵,和numberpy一样的操作，可以设置数据类型，查询shape等

In [4]:
x=torch.zeros(5,3,dtype=torch.long)
x=torch.zeros(5,3).long()
x.dtype

torch.int64

直接从数据中构建tensor

In [5]:
x=torch.tensor([5.3,3])
x

tensor([5.3000, 3.0000])

从已有的tensor中构建出新的tensor，会复用原有tensor的数据类型等信息。也可以明确指定tensor的数据类型

In [6]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

生成和已有的tensor一样的shape的随机数矩阵，可以指定类型

In [7]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[-1.3908, -1.2664, -0.9061],
        [ 0.1129, -0.5327, -0.1835],
        [-0.2790,  0.2534, -1.2388],
        [ 0.2851,  0.0080,  0.3084],
        [-0.3627, -0.9975, -0.4327]])

In [8]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

生成和已有的tensor一样的shape的随机数矩阵，可以指定类型

In [9]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[-2.0594,  0.1367,  0.4106],
        [ 1.1327, -0.2244,  0.9997],
        [ 0.8423,  1.3963,  0.1467],
        [-0.7257,  0.6424, -1.5615],
        [-1.2722, -0.6785, -0.7650]])

获取tensor的尺寸

In [12]:
x.shape

torch.Size([5, 3])

torch的操作符运算

In [52]:
y=torch.rand(5,3)
y

tensor([[0.0744, 0.1148, 0.6163],
        [0.5723, 0.8796, 0.7599],
        [0.3265, 0.3368, 0.2739],
        [0.0556, 0.9895, 0.1049],
        [0.3726, 0.4788, 0.7022]])

In [15]:
x+y

tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])

In [16]:
torch.add(x,y)

tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])

使用out会减少一次内存分配

In [18]:
result=torch.empty(5,3)
# torch.add(x,y,out=result)
# result=torch.add(x,y)
print(result)
result=x+y
result

tensor([[2.7049e-17, 4.5821e-41, 2.7049e-17],
        [4.5821e-41, 6.6815e+15, 3.0739e-41],
        [1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.5821e-41],
        [0.0000e+00, 0.0000e+00, 4.6243e-44]])
tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])
tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])


tensor([[-1.2806,  0.6266,  0.8453],
        [ 1.2708,  0.0185,  1.0680],
        [ 1.8327,  1.7707,  1.0565],
        [-0.0963,  0.7992, -1.3724],
        [-0.8977, -0.0333, -0.2837]])

In [23]:
y
y.add_(x)
y

tensor([[-3.3399,  0.7633,  1.2560],
        [ 2.4035, -0.2059,  2.0677],
        [ 2.6750,  3.1670,  1.2032],
        [-0.8221,  1.4417, -2.9340],
        [-2.1699, -0.7118, -1.0487]])

In [47]:
x=torch.randn(4,4)
x

tensor([[ 0.4096,  1.1041, -0.5462,  0.1856],
        [-0.1747,  0.5966, -1.2375, -0.8923],
        [-1.5111,  0.1223, -0.4714,  0.0083],
        [-0.3921,  0.8738,  0.1272, -0.3974]])

In [36]:
y=x.view(16)
z=x.view(8,-1)
y
z

ValueError: only one element tensors can be converted to Python scalars

如果tensor只有一个元素  可以用item直接获取值

In [38]:
x=torch.tensor([1])
x.item()

1

In [59]:
y

tensor([[0.0744, 0.1148, 0.6163],
        [0.5723, 0.8796, 0.7599],
        [0.3265, 0.3368, 0.2739],
        [0.0556, 0.9895, 0.1049],
        [0.3726, 0.4788, 0.7022]])

In [58]:
y.transpose(-1,0)

tensor([[0.0744, 0.5723, 0.3265, 0.0556, 0.3726],
        [0.1148, 0.8796, 0.3368, 0.9895, 0.4788],
        [0.6163, 0.7599, 0.2739, 0.1049, 0.7022]])

tensor 转 numpy 共享一段内存，一个改另一个也改

In [61]:
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [71]:
b=a.numpy()
b

array([1., 2., 2., 1., 1.], dtype=float32)

In [72]:
a[2]=2
b

array([1., 2., 2., 1., 1.], dtype=float32)

In [ ]:
c=torch.from_numpy(b)
c
c[3]=5
a

## torch 在gpu上运行

In [ ]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

转numpy

In [ ]:
z.cpu().data.numpy()
z.to("cpu").data.numpy()

## numpy实现两层神经网络


一个全连接的ReLu神经网络，一个隐藏层 没有bias 用x预测y 使用L2 loss

- $ h=W_1x+b $
- $ a=max(0,h) $
- $ y_{hat}=W_2a+b_2 $

计算前向神经网络 loss  和反向传播

- forward pass
- loss 
- backward pass

tensor([1., 2., 2., 5., 1.])

## torch 在gpu上运行

In [77]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

False

转numpy

In [ ]:
z.cpu().data.numpy()
z.to("cpu").data.numpy()

## numpy实现两层神经网络


一个全连接的ReLu神经网络，一个隐藏层 没有bias 用x预测y 使用L2 loss

- $ h=W_1x+b $
- $ a=max(0,h) $
- $ y_{hat}=W_2a+b_2 $

计算前向神经网络 loss  和反向传播

- forward pass
- loss 
- backward pass